In [1]:
import pandas as pd

In [3]:
heart_data = pd.read_csv('Data/heart-disease.csv')

In [5]:
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
X = heart_data.drop("target", axis = 1)
y = heart_data.target

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [8]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

clf.fit(X_train, y_train)

RandomForestClassifier()

Now the model is fit and we can check the performance of the model based on the values that we will get as output after predcting the values

In [9]:
# First way to get the score of the model from the values

clf.score(X_test, y_test)

0.819672131147541

In [10]:
# Another way to get the score of the model

y_pred = clf.predict(X_test)

y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [13]:
import numpy as np
np.array(y_test)

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1], dtype=int64)

In [14]:
np.mean(y_test == y_pred)

0.819672131147541

In [15]:
# Third way to get the accuracy of the model from the predictions made from the database

from sklearn.metrics import accuracy_score

score = accuracy_score(y_pred, y_test)

score

0.819672131147541

Now lets see what does the function `clf.predict_proba()` is used for

In [17]:
clf.predict_proba(X_test)
# it is used to get the probability of success or the failure of the predictions in the dataset

array([[0.08, 0.92],
       [0.01, 0.99],
       [0.93, 0.07],
       [0.32, 0.68],
       [0.46, 0.54],
       [0.33, 0.67],
       [0.13, 0.87],
       [0.2 , 0.8 ],
       [0.05, 0.95],
       [0.01, 0.99],
       [0.69, 0.31],
       [0.41, 0.59],
       [0.56, 0.44],
       [0.94, 0.06],
       [0.38, 0.62],
       [0.35, 0.65],
       [0.47, 0.53],
       [0.87, 0.13],
       [0.92, 0.08],
       [0.64, 0.36],
       [0.5 , 0.5 ],
       [0.79, 0.21],
       [0.83, 0.17],
       [0.47, 0.53],
       [0.83, 0.17],
       [0.18, 0.82],
       [0.43, 0.57],
       [0.68, 0.32],
       [0.47, 0.53],
       [0.85, 0.15],
       [0.65, 0.35],
       [0.24, 0.76],
       [0.28, 0.72],
       [0.41, 0.59],
       [1.  , 0.  ],
       [0.36, 0.64],
       [0.71, 0.29],
       [0.1 , 0.9 ],
       [0.29, 0.71],
       [0.13, 0.87],
       [0.06, 0.94],
       [0.9 , 0.1 ],
       [0.01, 0.99],
       [0.02, 0.98],
       [0.02, 0.98],
       [0.68, 0.32],
       [0.12, 0.88],
       [0.09,

### The values can be predicted by using the regression algorithm also

In [18]:
from sklearn.datasets import fetch_california_housing

In [20]:
housing_data = fetch_california_housing()

In [21]:
housing_data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [23]:
import pandas as pd

In [24]:
housing_df = pd.DataFrame(housing_data["data"], 
                         columns=housing_data["feature_names"]
                         )

In [25]:
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [26]:
housing_df["target"] = housing_data["target"]

In [29]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [31]:
X = housing_df.drop('target', axis=1)
y = housing_df.target

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [34]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(X_train, y_train)

RandomForestRegressor()

getting the score based on the `score()` method

In [35]:
model.score(X_test, y_test)

0.8082605041859301

In [37]:
y_pred = model.predict(X_test)
y_pred

array([2.8611704, 1.68698  , 1.96607  , ..., 1.01397  , 0.48846  ,
       0.75125  ])

In [38]:
np.array(y_test)

array([2.908, 1.618, 2.616, ..., 0.75 , 0.491, 0.708])

In [41]:
np.mean(y_pred == y_test)
# This has given answer here zero as this is regression problems and not classification
# Hence there is zero possibility that two predicted and actual values being same

0.0

In [42]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_pred, y_test)

0.32449145772771343