In [4]:
import numpy as np

## Datatypes and attributes

In [5]:
# numpy can have any dimensional array i.e ndarray

In [6]:
a1 = np.array([1,2,3,4,5,6])

In [7]:
a1

array([1, 2, 3, 4, 5, 6])

In [8]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1,2,3],
             [4,5,6],
              [4.5,6.2,9.5]])

In [11]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [4.5, 6.2, 9.5]])

In [13]:
# we can even type and create more number dimensional array also
a3 = np.array([[[1,2,3],
               [4,5,6],
              [7,8,9]],
              [[10,11,12],
               [13,14,15],
              [16,17,18]]])

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
# we can get the shape of the array based on the data that we will be getting

In [19]:
a1.shape
# here it is 6 because there are 6 numbers in the array

(6,)

In [20]:
a2.shape

(3, 3)

In [21]:
a3.shape

(2, 3, 3)

In [22]:
# we can even get and see how many dimensional the array is using ndim
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [23]:
# we can even get the datatype of all the elements into the arrays
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [24]:
# we can also get the number of elements in the array
a1.size, a2.size, a3.size

(6, 9, 18)

In [25]:
# we can get what type of datatype they are here all of them are ndarray
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [26]:
# Create a DataFrame from the numpy array

In [27]:
import pandas as pd

In [28]:
dataframe = pd.DataFrame(a1)

In [29]:
dataframe

0
0  1
1  2
2  3
3  4
4  5
5  6

In [30]:
dataframe2 = pd.DataFrame(a2)

In [31]:
dataframe2

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  4.5  6.2  9.5

In [33]:
# dataframe3 = pd.DataFrame(a3)
# It will give us the error as pandas dataframe must have at most 2d array as input

## Creating Numpy array

In [34]:
sample_array = np.array([1,2,3,4,5,6,7,8,9])

In [35]:
sample_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# What if we want to create the array which will have all the values defined for us

In [37]:
ones_array = np.ones((2,3))
# Signature: np.ones(shape, dtype=None, order='C', *, like=None)
# Docstring:
# Return a new array of given shape and type, filled with ones.

In [38]:
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
ones_array.dtype

dtype('float64')

In [40]:
type(ones_array)

numpy.ndarray

In [41]:
zeros_array = np.zeros((2,3))

In [42]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# np.arange(start, stop, step)
# Here the start is inclusive, stop is exclusive and step is how many number the value should inceament as they are fiiled in the proccess
range_array = np.arange(1, 11, 1)

In [46]:
range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# What if we want to have the numbers in the array which will be generated by the random numbers in the array
# Here the random.randint will take three arguements low which will be the number from where the generation of random numbers will start to get
# Then there will be a number high which will be used for the purpose of getting the upper bound of the number where we wish to get the numbers to end
# And then there is the parameter size which will be used for the purpose of having the numbers such that these will be used to determine the size of the array
random_array = np.random.randint(0, 15, size = (3,3))

In [48]:
random_array

array([[14,  0,  4],
       [ 0,  3,  0],
       [13,  3, 11]])

In [54]:
random_list = np.random.randint(0,21, size = 15)
# here we have given the size in the form of numbers hence it will create the list which will be one dimensional

In [55]:
random_list

array([11,  7, 15,  3, 13, 13, 14, 19, 16, 20,  0, 10, 10,  7, 19])

In [58]:
# random.random will get the input as size and then create the numbers which will be in the interval 0 and 1
random_array2 = np.random.random((5,3))

In [59]:
random_array2

array([[0.31151088, 0.79718252, 0.4885638 ],
       [0.84156323, 0.40339096, 0.68770484],
       [0.29477262, 0.68630509, 0.79114108],
       [0.3782815 , 0.75394433, 0.6014657 ],
       [0.98438347, 0.55859445, 0.82026242]])

In [62]:
random_array3 = np.random.rand(5,3)
# This is also used to get the random numbers in the numpy array

In [63]:
random_array3

array([[0.48557978, 0.32342889, 0.08826322],
       [0.95376776, 0.99862399, 0.73481492],
       [0.24530045, 0.54207459, 0.4817443 ],
       [0.1294141 , 0.20230708, 0.49568099],
       [0.92254917, 0.43663159, 0.04430931]])

In [64]:
# These numbers are generated by using the numpy seed

## Random Seed

In [66]:
# The random numbers are not actually random but they are pseudo random numbers
# They are generated using random seed

In [67]:
random_array4 = np.random.randint(10, size=(5,3))

In [68]:
random_array4

array([[4, 1, 1],
       [2, 3, 1],
       [2, 6, 1],
       [3, 5, 9],
       [0, 4, 3]])

In [69]:
# here if we refresh the tab then we will be able to see that the array will have the differnt random numbers every time we make a refresh
# But what if we want to share our code then will it be possible for other collegue of ours to get the exact random numbers so that it will be easy to reproduce the experiment that we have created

In [73]:
np.random.seed(78)
random_array5 = np.random.randint(15, size = (3,3))
random_array5
# here we have created and enabled the random seed number 78 here
# Hence it will generate the exact copy of the numbers every time
# Hence it is called as the random numbers that are generated by the random function are

array([[ 5,  6,  7],
       [ 8,  9,  6],
       [ 8, 13,  4]])

In [74]:
np.random.seed(101)
random_array6 = np.random.random((3,3))

In [77]:
random_array6

array([[0.51639863, 0.57066759, 0.02847423],
       [0.17152166, 0.68527698, 0.83389686],
       [0.30696622, 0.89361308, 0.72154386]])

In [78]:
# Look above values also didn't change

## Viewing arrays and metrices

In [79]:
# Now we have lot of array and hence we might need to get the unique values in the array

In [80]:
unique_in_5 = np.unique(random_array5)

In [81]:
unique_in_5

array([ 4,  5,  6,  7,  8,  9, 13])

In [82]:
# Hence we have get the unique values in the array
# It can be used and applied to any dimensional array

In [83]:
# To acces the elements of the array we can make use of the square bracket to get the elements at that index
# Depending on the dimension of the array this will give us either single element or it can also give us the another array of one dimension less

In [84]:
a1[0]

1

In [85]:
a2[0]

array([1., 2., 3.])

In [86]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
# Look what we got as first element of the array it was either single element or whole array also

In [88]:
# We can make use of the slicing operator in the indexing function also

In [89]:
a1[2:5]

array([3, 4, 5])

In [92]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [93]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])